server:
  port: 8020

spring:
  application:
    name: rms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

das:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
